### PR TITLE
tmr_description: fix dependency to tm_msgs

### PR DESCRIPTION
**Pull request by yotabits**
Set the correct package name as a dependency.

### CODE REVIEW

**Review by Yuki-cpp — APPROVED** [review]
LGTM
@haudren I guess you should have a look at this before it goes live

**Review by haudren — APPROVED** [review]
:+1: Easy fix !

**Comment by hocjordan** [comment]
@yotabits do you want to merge this?

**Review by hocjordan — APPROVED** [review]

**Comment by yotabits** [comment]
> @yotabits do you want to merge this?

@hocjordan Thank you for the reminder ;)

**Pull request merged**
